/**
 * 英雄数据映射表：英文 key → { 中文称号, 中文名 }
 * 数据来源：Data Dragon champion.json (zh_CN)
 */

export interface ChampionInfo {
    title: string        // 中文称号，如"时间刺客"
    name: string         // 中文名，如"艾克"
    nicknames?: string[] // 玩家常用外号，如"艾克"、"时间管理大师" 等
}

// key → title, name
const CHAMPION_DATA: Record<string, ChampionInfo> = {
    Aatrox: { title: '暗裔剑魔', name: '亚托克斯' },
    Ahri: { title: '九尾妖狐', name: '阿狸' },
    Akali: { title: '离群之刺', name: '阿卡丽' },
    Akshan: { title: '影哨', name: '阿克尚' },
    Alistar: { title: '牛头酋长', name: '阿利斯塔' },
    Ambessa: { title: '铁血狼母', name: '安蓓萨' },
    Amumu: { title: '殇之木乃伊', name: '阿木木' },
    Anivia: { title: '冰晶凤凰', name: '艾尼维亚' },
    Annie: { title: '黑暗之女', name: '安妮' },
    Aphelios: { title: '残月之肃', name: '厄斐琉斯' },
    Ashe: { title: '寒冰射手', name: '艾希', nicknames: ['后裔'] },
    AurelionSol: { title: '铸星龙王', name: '奥瑞利安·索尔' },
    Aurora: { title: '双界灵兔', name: '阿萝拉' },
    Azir: { title: '沙漠皇帝', name: '阿兹尔', nicknames: ['黄鸡', '沙皇'] },
    Bard: { title: '星界游神', name: '巴德' },
    Belveth: { title: '虚空女皇', name: '卑尔维斯', nicknames: ['阿尔卑斯'] },
    Blitzcrank: { title: '蒸汽机器人', name: '布里茨', nicknames: ['蒸饭机器人'] },
    Brand: { title: '复仇焰魂', name: '布兰德', nicknames: ['火男'] },
    Braum: { title: '弗雷尔卓德之心', name: '布隆', nicknames: ['防盗门'] },
    Briar: { title: '狂厄蔷薇', name: '贝蕾亚' },
    Caitlyn: { title: '皮城女警', name: '凯特琳' },
    Camille: { title: '青钢影', name: '卡蜜尔' },
    Cassiopeia: { title: '魔蛇之拥', name: '卡西奥佩娅', nicknames: ['蛇女', '大蛇丸'] },
    Chogath: { title: '虚空恐惧', name: '科加斯', nicknames: ['大虫子'] },
    Corki: { title: '英勇投弹手', name: '库奇', nicknames: ['飞机'] },
    Darius: { title: '诺克萨斯之手', name: '德莱厄斯', nicknames: ['诺手'] },
    Diana: { title: '皎月女神', name: '黛安娜' },
    Draven: { title: '荣耀行刑官', name: '德莱文', nicknames: ['文森特', '德子'] },
    DrMundo: { title: '祖安狂人', name: '蒙多医生' },
    Ekko: { title: '时间刺客', name: '艾克', nicknames: ['艾克', '时间管理大师', '罗志祥'] },
    Elise: { title: '蜘蛛女皇', name: '伊莉丝' },
    Evelynn: { title: '痛苦之拥', name: '伊芙琳', nicknames: ['寡妇'] },
    Ezreal: { title: '探险家', name: '伊泽瑞尔', nicknames: ['ez', '小黄毛'] },
    Fiddlesticks: { title: '远古恐惧', name: '费德提克', nicknames: ['稻草人'] },
    Fiora: { title: '无双剑姬', name: '菲奥娜', nicknames: ['jj'] },
    Fizz: { title: '潮汐海灵', name: '菲兹', nicknames: ['小鱼人', '娃娃鱼'] },
    Galio: { title: '正义巨像', name: '加里奥' },
    Gangplank: { title: '海洋之灾', name: '普朗克', nicknames: ['船长'] },
    Garen: { title: '德玛西亚之力', name: '盖伦' },
    Gnar: { title: '迷失之牙', name: '纳尔' },
    Gragas: { title: '酒桶', name: '古拉加斯', nicknames: ['啤酒人'] },
    Graves: { title: '法外狂徒', name: '格雷福斯', nicknames: ['男枪', '狐臭'] },
    Gwen: { title: '灵罗娃娃', name: '格温' },
    Hecarim: { title: '战争之影', name: '赫卡里姆', nicknames: ['人马'] },
    Heimerdinger: { title: '大发明家', name: '黑默丁格', nicknames: ['大头'] },
    Hwei: { title: '异画师', name: '彗', nicknames: ['毛笔人'] },
    Illaoi: { title: '海兽祭司', name: '俄洛伊' },
    Irelia: { title: '刀锋舞者', name: '艾瑞莉娅', nicknames: ['刀妹'] },
    Ivern: { title: '翠神', name: '艾翁', nicknames: ['蔡徐坤'] },
    Janna: { title: '风暴之怒', name: '迦娜', nicknames: ['风女'] },
    JarvanIV: { title: '德玛西亚皇子', name: '嘉文四世', nicknames: ['皇子', '周杰伦'] },
    Jax: { title: '武器大师', name: '贾克斯', nicknames: ['jax', '贾老汉'] },
    Jayce: { title: '未来守护者', name: '杰斯', nicknames: ['杰西'] },
    Jhin: { title: '戏命师', name: '烬', nicknames: ['望远镜'] },
    Jinx: { title: '暴走萝莉', name: '金克丝' },
    Kaisa: { title: '虚空之女', name: '卡莎' },
    Kalista: { title: '复仇之矛', name: '卡莉丝塔', nicknames: ['滑板鞋'] },
    Karma: { title: '天启者', name: '卡尔玛', nicknames: ['扇子妈'] },
    Karthus: { title: '死亡颂唱者', name: '卡尔萨斯', nicknames: ['死歌'] },
    Kassadin: { title: '虚空行者', name: '卡萨丁' },
    Katarina: { title: '不祥之刃', name: '卡特琳娜' },
    Kayle: { title: '正义天使', name: '凯尔', nicknames: ['天使'] },
    Kayn: { title: '影流之镰', name: '凯隐' },
    Kennen: { title: '狂暴之心', name: '凯南', nicknames: ['电耗子'] },
    Khazix: { title: '虚空掠夺者', name: '卡兹克', nicknames: ['螳螂', '喜之郎'] },
    Kindred: { title: '永猎双子', name: '千珏' },
    Kled: { title: '暴怒骑士', name: '克烈' },
    KogMaw: { title: '深渊巨口', name: '克格莫', nicknames: ['大嘴'] },
    KSante: { title: '纳祖芒荣耀', name: '奎桑提' },
    Leblanc: { title: '诡术妖姬', name: '乐芙兰' },
    LeeSin: { title: '盲僧', name: '李青', nicknames: ['瞎子', '李青', '达摩'] },
    Leona: { title: '曙光女神', name: '蕾欧娜', nicknames: ['日女'] },
    Lillia: { title: '含羞蓓蕾', name: '莉莉娅' },
    Lissandra: { title: '冰霜女巫', name: '丽桑卓', nicknames: ['冰女'] },
    Locke: { title: '灰烬驱魔人', name: '洛克' },
    Lucian: { title: '圣枪游侠', name: '卢锡安', nicknames: ['奥巴马'] },
    Lulu: { title: '仙灵女巫', name: '璐璐', nicknames: ['紫皮大蒜'] },
    Lux: { title: '光辉女郎', name: '拉克丝' },
    Malphite: { title: '熔岩巨兽', name: '墨菲特', nicknames: ['石头人'] },
    Malzahar: { title: '虚空先知', name: '玛尔扎哈', nicknames: ['梅毒'] },
    Maokai: { title: '扭曲树精', name: '茂凯', nicknames: ['大树'] },
    MasterYi: { title: '无极剑圣', name: '易' },
    Mel: { title: '流光镜影', name: '梅尔' },
    Milio: { title: '明烛', name: '米利欧', nicknames: ['丁真'] },
    MissFortune: { title: '赏金猎人', name: '厄运小姐', nicknames: ['女枪'] },
    MonkeyKing: { title: '齐天大圣', name: '孙悟空', nicknames: ['猴子'] },
    Mordekaiser: { title: '铁铠冥魂', name: '莫德凯撒', nicknames: ['铁男'] },
    Morgana: { title: '堕落天使', name: '莫甘娜' },
    Naafiri: { title: '百裂冥犬', name: '纳亚菲利' },
    Nami: { title: '唤潮鲛姬', name: '娜美' },
    Nasus: { title: '沙漠死神', name: '内瑟斯', nicknames: ['狗头'] },
    Nautilus: { title: '深海泰坦', name: '诺提勒斯' },
    Neeko: { title: '万花通灵', name: '妮蔻' },
    Nidalee: { title: '狂野女猎手', name: '奈德丽', nicknames: ['豹女'] },
    Nilah: { title: '不羁之悦', name: '尼菈' },
    Nocturne: { title: '永恒梦魇', name: '魔腾' },
    Nunu: { title: '雪原双子', name: '努努和威朗普' },
    Olaf: { title: '狂战士', name: '奥拉夫' },
    Orianna: { title: '发条魔灵', name: '奥莉安娜' },
    Ornn: { title: '山隐之焰', name: '奥恩', nicknames: ['山羊'] },
    Pantheon: { title: '不屈之枪', name: '潘森' },
    Poppy: { title: '圣锤之毅', name: '波比' },
    Pyke: { title: '血港鬼影', name: '派克' },
    Qiyana: { title: '元素女皇', name: '奇亚娜' },
    Quinn: { title: '德玛西亚之翼', name: '奎因' },
    Rakan: { title: '幻翎', name: '洛' },
    Rammus: { title: '披甲龙龟', name: '拉莫斯' },
    RekSai: { title: '虚空遁地兽', name: '雷克塞', nicknames: ['挖机'] },
    Rell: { title: '镕铁少女', name: '芮尔' },
    Renata: { title: '炼金男爵', name: '烈娜塔·戈拉斯克' },
    Renekton: { title: '荒漠屠夫', name: '雷克顿', nicknames: ['鳄鱼'] },
    Rengar: { title: '傲之追猎者', name: '雷恩加尔', nicknames: ['狮子狗'] },
    Riven: { title: '放逐之刃', name: '锐雯', nicknames: ['瑞文'] },
    Rumble: { title: '机械公敌', name: '兰博' },
    Ryze: { title: '符文法师', name: '瑞兹' },
    Samira: { title: '沙漠玫瑰', name: '莎弥拉' },
    Sejuani: { title: '北地之怒', name: '瑟庄妮', nicknames: ['猪妹'] },
    Senna: { title: '涤魂圣枪', name: '赛娜' },
    Seraphine: { title: '星籁歌姬', name: '萨勒芬妮', nicknames: ['酸辣粉'] },
    Sett: { title: '腕豪', name: '瑟提' },
    Shaco: { title: '恶魔小丑', name: '萨科' },
    Shen: { title: '暮光之眼', name: '慎' },
    Shyvana: { title: '龙血武姬', name: '希瓦娜', nicknames: ['龙女'] },
    Singed: { title: '炼金术士', name: '辛吉德' },
    Sion: { title: '亡灵战神', name: '赛恩' },
    Sivir: { title: '战争女神', name: '希维尔', nicknames: ['轮子妈'] },
    Skarner: { title: '上古领主', name: '斯卡纳', nicknames: ['蝎子'] },
    Smolder: { title: '炽炎雏龙', name: '斯莫德', nicknames: ['小火龙'] },
    Sona: { title: '琴瑟仙女', name: '娑娜', nicknames: ['琴女'] },
    Soraka: { title: '众星之子', name: '索拉卡', nicknames: ['奶妈'] },
    Swain: { title: '诺克萨斯统领', name: '斯维因', nicknames: ['乌鸦'] },
    Sylas: { title: '解脱者', name: '塞拉斯' },
    Syndra: { title: '暗黑元首', name: '辛德拉' },
    TahmKench: { title: '河流之王', name: '塔姆' },
    Taliyah: { title: '岩雀', name: '塔莉垭' },
    Talon: { title: '刀锋之影', name: '泰隆', nicknames: ['男刀'] },
    Taric: { title: '瓦洛兰之盾', name: '塔里克' },
    Teemo: { title: '迅捷斥候', name: '提莫' },
    Thresh: { title: '魂锁典狱长', name: '锤石' },
    Tristana: { title: '麦林炮手', name: '崔丝塔娜', nicknames: ['小炮'] },
    Trundle: { title: '巨魔之王', name: '特朗德尔' },
    Tryndamere: { title: '蛮族之王', name: '泰达米尔', nicknames: ['蛮王'] },
    TwistedFate: { title: '卡牌大师', name: '崔斯特' },
    Twitch: { title: '瘟疫之源', name: '图奇', nicknames: ['老鼠'] },
    Udyr: { title: '兽灵行者', name: '乌迪尔' },
    Urgot: { title: '无畏战车', name: '厄加特', nicknames: ['螃蟹'] },
    Varus: { title: '惩戒之箭', name: '韦鲁斯' },
    Vayne: { title: '暗夜猎手', name: '薇恩', nicknames: ['vn'] },
    Veigar: { title: '邪恶小法师', name: '维迦' },
    Velkoz: { title: '虚空之眼', name: '维克兹' },
    Vex: { title: '愁云使者', name: '薇古丝', nicknames: ['熬夜波比'] },
    Vi: { title: '皮城执法官', name: '蔚' },
    Viego: { title: '破败之王', name: '佛耶戈' },
    Viktor: { title: '机械先驱', name: '维克托' },
    Vladimir: { title: '猩红收割者', name: '弗拉基米尔', nicknames: ['吸血鬼'] },
    Volibear: { title: '不灭狂雷', name: '沃利贝尔', nicknames: ['狗熊'] },
    Warwick: { title: '祖安怒兽', name: '沃里克' },
    Wukong: { title: '齐天大圣', name: '孙悟空', nicknames: ['猴子'] },
    Xayah: { title: '逆羽', name: '霞' },
    Xerath: { title: '远古巫灵', name: '泽拉斯' },
    XinZhao: { title: '德邦总管', name: '赵信' },
    Yasuo: { title: '疾风剑豪', name: '亚索', nicknames: ['压缩', '快乐风男', '孤儿'] },
    Yone: { title: '封魔剑魂', name: '永恩' },
    Yorick: { title: '牧魂人', name: '约里克' },
    Yunara: { title: '不破之誓', name: '芸阿娜' },
    Yuumi: { title: '魔法猫咪', name: '悠米' },
    Zaahen: { title: '不落魔锋', name: '亚恒' },
    Zac: { title: '生化魔人', name: '扎克', nicknames: ['粑粑人'] },
    Zed: { title: '影流之主', name: '劫', nicknames: ['飞镖人'] },
    Zeri: { title: '祖安花火', name: '泽丽' },
    Ziggs: { title: '爆破鬼才', name: '吉格斯', nicknames: ['炸弹人'] },
    Zilean: { title: '时光守护者', name: '基兰', nicknames: ['老头'] },
    Zoe: { title: '暮光星灵', name: '佐伊' },
    Zyra: { title: '荆棘之兴', name: '婕拉' },
}

/**
 * 根据英文 key 获取英雄信息（中文称号 + 中文名）。
 * 如果找不到，返回 undefined。
 */
export function getChampionInfo(key: string): ChampionInfo | undefined {
    return CHAMPION_DATA[key]
}
