/**
 * 英雄数据映射表：英文 key → { 中文称号, 中文名, 分路 }
 * 数据来源：Data Dragon champion.json (zh_CN)
 */

export type ChampionRole = 'Top' | 'Jungle' | 'Mid' | 'ADC' | 'Support'

export interface ChampionInfo {
    title: string        // 中文称号，如"时间刺客"
    name: string         // 中文名，如"艾克"
    nicknames?: string[] // 玩家常用外号，如"艾克"、"时间管理大师" 等
    roles?: ChampionRole[] // 英雄分路/定位
}

// key → title, name, roles
const CHAMPION_DATA: Record<string, ChampionInfo> = {
    Aatrox: { title: '暗裔剑魔', name: '亚托克斯', roles: ['Top'] },
    Ahri: { title: '九尾妖狐', name: '阿狸', roles: ['Mid'] },
    Akali: { title: '离群之刺', name: '阿卡丽', roles: ['Top', 'Mid'] },
    Akshan: { title: '影哨', name: '阿克尚', roles: ['Mid'] },
    Alistar: { title: '牛头酋长', name: '阿利斯塔', roles: ['Support'] },
    Ambessa: { title: '铁血狼母', name: '安蓓萨', roles: ['Top'] },
    Amumu: { title: '殇之木乃伊', name: '阿木木', roles: ['Jungle', 'Support'] },
    Anivia: { title: '冰晶凤凰', name: '艾尼维亚', roles: ['Mid'] },
    Annie: { title: '黑暗之女', name: '安妮', roles: ['Mid'] },
    Aphelios: { title: '残月之肃', name: '厄斐琉斯', roles: ['ADC'] },
    Ashe: { title: '寒冰射手', name: '艾希', nicknames: ['后裔'], roles: ['ADC', 'Support'] },
    AurelionSol: { title: '铸星龙王', name: '奥瑞利安·索尔', roles: ['Mid'] },
    Aurora: { title: '双界灵兔', name: '阿萝拉', roles: ['Mid'] },
    Azir: { title: '沙漠皇帝', name: '阿兹尔', nicknames: ['黄鸡', '沙皇'], roles: ['Mid'] },
    Bard: { title: '星界游神', name: '巴德', roles: ['Support'] },
    Belveth: { title: '虚空女皇', name: '卑尔维斯', nicknames: ['阿尔卑斯'], roles: ['Jungle'] },
    Blitzcrank: { title: '蒸汽机器人', name: '布里茨', nicknames: ['蒸饭机器人'], roles: ['Support'] },
    Brand: { title: '复仇焰魂', name: '布兰德', nicknames: ['火男'], roles: ['Mid', 'Support', 'Jungle'] },
    Braum: { title: '弗雷尔卓德之心', name: '布隆', nicknames: ['防盗门'], roles: ['Support'] },
    Briar: { title: '狂厄蔷薇', name: '贝蕾亚', roles: ['Jungle'] },
    Caitlyn: { title: '皮城女警', name: '凯特琳', roles: ['ADC'] },
    Camille: { title: '青钢影', name: '卡蜜尔', roles: ['Top'] },
    Cassiopeia: { title: '魔蛇之拥', name: '卡西奥佩娅', nicknames: ['蛇女', '大蛇丸'], roles: ['Mid'] },
    Chogath: { title: '虚空恐惧', name: '科加斯', nicknames: ['大虫子'], roles: ['Top', 'Jungle'] },
    Corki: { title: '英勇投弹手', name: '库奇', nicknames: ['飞机'], roles: ['Mid', 'ADC'] },
    Darius: { title: '诺克萨斯之手', name: '德莱厄斯', nicknames: ['诺手'], roles: ['Top'] },
    Diana: { title: '皎月女神', name: '黛安娜', roles: ['Jungle', 'Mid'] },
    Draven: { title: '荣耀行刑官', name: '德莱文', nicknames: ['文森特', '德子'], roles: ['ADC'] },
    DrMundo: { title: '祖安狂人', name: '蒙多医生', roles: ['Top', 'Jungle'] },
    Ekko: { title: '时间刺客', name: '艾克', nicknames: ['艾克', '时间管理大师', '罗志祥'], roles: ['Jungle', 'Mid'] },
    Elise: { title: '蜘蛛女皇', name: '伊莉丝', roles: ['Jungle'] },
    Evelynn: { title: '痛苦之拥', name: '伊芙琳', nicknames: ['寡妇'], roles: ['Jungle'] },
    Ezreal: { title: '探险家', name: '伊泽瑞尔', nicknames: ['ez', '小黄毛'], roles: ['ADC'] },
    Fiddlesticks: { title: '远古恐惧', name: '费德提克', nicknames: ['稻草人'], roles: ['Jungle', 'Support'] },
    Fiora: { title: '无双剑姬', name: '菲奥娜', nicknames: ['jj'], roles: ['Top'] },
    Fizz: { title: '潮汐海灵', name: '菲兹', nicknames: ['小鱼人', '娃娃鱼'], roles: ['Mid'] },
    Galio: { title: '正义巨像', name: '加里奥', roles: ['Mid', 'Support'] },
    Gangplank: { title: '海洋之灾', name: '普朗克', nicknames: ['船长'], roles: ['Top', 'Mid'] },
    Garen: { title: '德玛西亚之力', name: '盖伦', roles: ['Top'] },
    Gnar: { title: '迷失之牙', name: '纳尔', roles: ['Top'] },
    Gragas: { title: '酒桶', name: '古拉加斯', nicknames: ['啤酒人'], roles: ['Jungle', 'Top'] },
    Graves: { title: '法外狂徒', name: '格雷福斯', nicknames: ['男枪', '狐臭'], roles: ['Jungle'] },
    Gwen: { title: '灵罗娃娃', name: '格温', roles: ['Top', 'Jungle'] },
    Hecarim: { title: '战争之影', name: '赫卡里姆', nicknames: ['人马'], roles: ['Jungle'] },
    Heimerdinger: { title: '大发明家', name: '黑默丁格', nicknames: ['大头'], roles: ['Mid', 'Support'] },
    Hwei: { title: '异画师', name: '彗', nicknames: ['毛笔人'], roles: ['Mid', 'Support'] },
    Illaoi: { title: '海兽祭司', name: '俄洛伊', roles: ['Top'] },
    Irelia: { title: '刀锋舞者', name: '艾瑞莉娅', nicknames: ['刀妹'], roles: ['Top', 'Mid'] },
    Ivern: { title: '翠神', name: '艾翁', nicknames: ['蔡徐坤'], roles: ['Jungle'] },
    Janna: { title: '风暴之怒', name: '迦娜', nicknames: ['风女'], roles: ['Support'] },
    JarvanIV: { title: '德玛西亚皇子', name: '嘉文四世', nicknames: ['皇子', '周杰伦'], roles: ['Jungle'] },
    Jax: { title: '武器大师', name: '贾克斯', nicknames: ['jax', '贾老汉'], roles: ['Top', 'Jungle'] },
    Jayce: { title: '未来守护者', name: '杰斯', nicknames: ['杰西'], roles: ['Top', 'Mid'] },
    Jhin: { title: '戏命师', name: '烬', nicknames: ['望远镜'], roles: ['ADC'] },
    Jinx: { title: '暴走萝莉', name: '金克丝', roles: ['ADC'] },
    Kaisa: { title: '虚空之女', name: '卡莎', roles: ['ADC', 'Mid'] },
    Kalista: { title: '复仇之矛', name: '卡莉丝塔', nicknames: ['滑板鞋'], roles: ['ADC'] },
    Karma: { title: '天启者', name: '卡尔玛', nicknames: ['扇子妈'], roles: ['Support', 'Mid'] },
    Karthus: { title: '死亡颂唱者', name: '卡尔萨斯', nicknames: ['死歌'], roles: ['Jungle', 'Mid'] },
    Kassadin: { title: '虚空行者', name: '卡萨丁', roles: ['Mid'] },
    Katarina: { title: '不祥之刃', name: '卡特琳娜', roles: ['Mid'] },
    Kayle: { title: '正义天使', name: '凯尔', nicknames: ['天使'], roles: ['Top', 'Mid'] },
    Kayn: { title: '影流之镰', name: '凯隐', roles: ['Jungle'] },
    Kennen: { title: '狂暴之心', name: '凯南', nicknames: ['电耗子'], roles: ['Top'] },
    Khazix: { title: '虚空掠夺者', name: '卡兹克', nicknames: ['螳螂', '喜之郎'], roles: ['Jungle'] },
    Kindred: { title: '永猎双子', name: '千珏', roles: ['Jungle'] },
    Kled: { title: '暴怒骑士', name: '克烈', roles: ['Top'] },
    KogMaw: { title: '深渊巨口', name: '克格莫', nicknames: ['大嘴'], roles: ['ADC'] },
    KSante: { title: '纳祖芒荣耀', name: '奎桑提', roles: ['Top'] },
    Leblanc: { title: '诡术妖姬', name: '乐芙兰', roles: ['Mid'] },
    LeeSin: { title: '盲僧', name: '李青', nicknames: ['瞎子', '李青', '达摩'], roles: ['Jungle'] },
    Leona: { title: '曙光女神', name: '蕾欧娜', nicknames: ['日女'], roles: ['Support'] },
    Lillia: { title: '含羞蓓蕾', name: '莉莉娅', roles: ['Jungle'] },
    Lissandra: { title: '冰霜女巫', name: '丽桑卓', nicknames: ['冰女'], roles: ['Mid'] },
    Locke: { title: '灰烬驱魔人', name: '洛克', roles: ['Mid', 'Jungle'] },
    Lucian: { title: '圣枪游侠', name: '卢锡安', nicknames: ['奥巴马'], roles: ['ADC'] },
    Lulu: { title: '仙灵女巫', name: '璐璐', nicknames: ['紫皮大蒜'], roles: ['Support'] },
    Lux: { title: '光辉女郎', name: '拉克丝', roles: ['Mid', 'Support'] },
    Malphite: { title: '熔岩巨兽', name: '墨菲特', nicknames: ['石头人'], roles: ['Top', 'Jungle', 'Support'] },
    Malzahar: { title: '虚空先知', name: '玛尔扎哈', nicknames: ['梅毒'], roles: ['Mid'] },
    Maokai: { title: '扭曲树精', name: '茂凯', nicknames: ['大树'], roles: ['Top', 'Jungle', 'Support'] },
    MasterYi: { title: '无极剑圣', name: '易', roles: ['Jungle'] },
    Mel: { title: '流光镜影', name: '梅尔', roles: ['Mid', 'Support'] },
    Milio: { title: '明烛', name: '米利欧', nicknames: ['丁真'], roles: ['Support'] },
    MissFortune: { title: '赏金猎人', name: '厄运小姐', nicknames: ['女枪'], roles: ['ADC'] },
    MonkeyKing: { title: '齐天大圣', name: '孙悟空', nicknames: ['猴子'], roles: ['Top', 'Jungle'] },
    Mordekaiser: { title: '铁铠冥魂', name: '莫德凯撒', nicknames: ['铁男'], roles: ['Top'] },
    Morgana: { title: '堕落天使', name: '莫甘娜', roles: ['Support', 'Jungle'] },
    Naafiri: { title: '百裂冥犬', name: '纳亚菲利', roles: ['Mid', 'Jungle'] },
    Nami: { title: '唤潮鲛姬', name: '娜美', roles: ['Support'] },
    Nasus: { title: '沙漠死神', name: '内瑟斯', nicknames: ['狗头'], roles: ['Top'] },
    Nautilus: { title: '深海泰坦', name: '诺提勒斯', roles: ['Support', 'Jungle'] },
    Neeko: { title: '万花通灵', name: '妮蔻', roles: ['Mid', 'Support'] },
    Nidalee: { title: '狂野女猎手', name: '奈德丽', nicknames: ['豹女'], roles: ['Jungle'] },
    Nilah: { title: '不羁之悦', name: '尼菈', roles: ['ADC'] },
    Nocturne: { title: '永恒梦魇', name: '魔腾', roles: ['Jungle'] },
    Nunu: { title: '雪原双子', name: '努努和威朗普', roles: ['Jungle'] },
    Olaf: { title: '狂战士', name: '奥拉夫', roles: ['Top', 'Jungle'] },
    Orianna: { title: '发条魔灵', name: '奥莉安娜', roles: ['Mid'] },
    Ornn: { title: '山隐之焰', name: '奥恩', nicknames: ['山羊'], roles: ['Top'] },
    Pantheon: { title: '不屈之枪', name: '潘森', roles: ['Top', 'Jungle', 'Support'] },
    Poppy: { title: '圣锤之毅', name: '波比', roles: ['Top', 'Jungle', 'Support'] },
    Pyke: { title: '血港鬼影', name: '派克', roles: ['Support'] },
    Qiyana: { title: '元素女皇', name: '奇亚娜', roles: ['Mid', 'Jungle'] },
    Quinn: { title: '德玛西亚之翼', name: '奎因', roles: ['Top'] },
    Rakan: { title: '幻翎', name: '洛', roles: ['Support'] },
    Rammus: { title: '披甲龙龟', name: '拉莫斯', roles: ['Jungle'] },
    RekSai: { title: '虚空遁地兽', name: '雷克塞', nicknames: ['挖机'], roles: ['Jungle'] },
    Rell: { title: '镕铁少女', name: '芮尔', roles: ['Support'] },
    Renata: { title: '炼金男爵', name: '烈娜塔·戈拉斯克', roles: ['Support'] },
    Renekton: { title: '荒漠屠夫', name: '雷克顿', nicknames: ['鳄鱼'], roles: ['Top'] },
    Rengar: { title: '傲之追猎者', name: '雷恩加尔', nicknames: ['狮子狗'], roles: ['Jungle', 'Top'] },
    Riven: { title: '放逐之刃', name: '锐雯', nicknames: ['瑞文'], roles: ['Top'] },
    Rumble: { title: '机械公敌', name: '兰博', roles: ['Top', 'Mid'] },
    Ryze: { title: '符文法师', name: '瑞兹', roles: ['Mid'] },
    Samira: { title: '沙漠玫瑰', name: '莎弥拉', roles: ['ADC'] },
    Sejuani: { title: '北地之怒', name: '瑟庄妮', nicknames: ['猪妹'], roles: ['Jungle'] },
    Senna: { title: '涤魂圣枪', name: '赛娜', roles: ['Support', 'ADC'] },
    Seraphine: { title: '星籁歌姬', name: '萨勒芬妮', nicknames: ['酸辣粉'], roles: ['Support', 'Mid'] },
    Sett: { title: '腕豪', name: '瑟提', roles: ['Top'] },
    Shaco: { title: '恶魔小丑', name: '萨科', roles: ['Jungle', 'Support'] },
    Shen: { title: '暮光之眼', name: '慎', roles: ['Top', 'Support'] },
    Shyvana: { title: '龙血武姬', name: '希瓦娜', nicknames: ['龙女'], roles: ['Jungle'] },
    Singed: { title: '炼金术士', name: '辛吉德', roles: ['Top'] },
    Sion: { title: '亡灵战神', name: '赛恩', roles: ['Top'] },
    Sivir: { title: '战争女神', name: '希维尔', nicknames: ['轮子妈'], roles: ['ADC'] },
    Skarner: { title: '上古领主', name: '斯卡纳', nicknames: ['蝎子'], roles: ['Jungle', 'Top'] },
    Smolder: { title: '炽炎雏龙', name: '斯莫德', nicknames: ['小火龙'], roles: ['ADC'] },
    Sona: { title: '琴瑟仙女', name: '娑娜', nicknames: ['琴女'], roles: ['Support'] },
    Soraka: { title: '众星之子', name: '索拉卡', nicknames: ['奶妈'], roles: ['Support'] },
    Swain: { title: '诺克萨斯统领', name: '斯维因', nicknames: ['乌鸦'], roles: ['Support', 'Mid'] },
    Sylas: { title: '解脱者', name: '塞拉斯', roles: ['Mid', 'Jungle', 'Top'] },
    Syndra: { title: '暗黑元首', name: '辛德拉', roles: ['Mid'] },
    TahmKench: { title: '河流之王', name: '塔姆', roles: ['Top', 'Support'] },
    Taliyah: { title: '岩雀', name: '塔莉垭', roles: ['Jungle', 'Mid'] },
    Talon: { title: '刀锋之影', name: '泰隆', nicknames: ['男刀'], roles: ['Mid', 'Jungle'] },
    Taric: { title: '瓦洛兰之盾', name: '塔里克', roles: ['Support'] },
    Teemo: { title: '迅捷斥候', name: '提莫', roles: ['Top'] },
    Thresh: { title: '魂锁典狱长', name: '锤石', roles: ['Support'] },
    Tristana: { title: '麦林炮手', name: '崔丝塔娜', nicknames: ['小炮'], roles: ['ADC', 'Mid'] },
    Trundle: { title: '巨魔之王', name: '特朗德尔', roles: ['Jungle', 'Top'] },
    Tryndamere: { title: '蛮族之王', name: '泰达米尔', nicknames: ['蛮王'], roles: ['Top'] },
    TwistedFate: { title: '卡牌大师', name: '崔斯特', roles: ['Mid'] },
    Twitch: { title: '瘟疫之源', name: '图奇', nicknames: ['老鼠'], roles: ['ADC', 'Jungle'] },
    Udyr: { title: '兽灵行者', name: '乌迪尔', roles: ['Jungle', 'Top'] },
    Urgot: { title: '无畏战车', name: '厄加特', nicknames: ['螃蟹'], roles: ['Top'] },
    Varus: { title: '惩戒之箭', name: '韦鲁斯', roles: ['ADC'] },
    Vayne: { title: '暗夜猎手', name: '薇恩', nicknames: ['vn'], roles: ['ADC', 'Top'] },
    Veigar: { title: '邪恶小法师', name: '维迦', roles: ['Mid'] },
    Velkoz: { title: '虚空之眼', name: '维克兹', roles: ['Support', 'Mid'] },
    Vex: { title: '愁云使者', name: '薇古丝', nicknames: ['熬夜波比'], roles: ['Mid'] },
    Vi: { title: '皮城执法官', name: '蔚', roles: ['Jungle'] },
    Viego: { title: '破败之王', name: '佛耶戈', roles: ['Jungle'] },
    Viktor: { title: '机械先驱', name: '维克托', roles: ['Mid'] },
    Vladimir: { title: '猩红收割者', name: '弗拉基米尔', nicknames: ['吸血鬼'], roles: ['Mid', 'Top'] },
    Volibear: { title: '不灭狂雷', name: '沃利贝尔', nicknames: ['狗熊'], roles: ['Jungle', 'Top'] },
    Warwick: { title: '祖安怒兽', name: '沃里克', roles: ['Jungle', 'Top'] },
    Wukong: { title: '齐天大圣', name: '孙悟空', nicknames: ['猴子'], roles: ['Top', 'Jungle'] },
    Xayah: { title: '逆羽', name: '霞', roles: ['ADC'] },
    Xerath: { title: '远古巫灵', name: '泽拉斯', roles: ['Support', 'Mid'] },
    XinZhao: { title: '德邦总管', name: '赵信', roles: ['Jungle'] },
    Yasuo: { title: '疾风剑豪', name: '亚索', nicknames: ['压缩', '快乐风男', '孤儿'], roles: ['Mid', 'Top'] },
    Yone: { title: '封魔剑魂', name: '永恩', roles: ['Mid', 'Top'] },
    Yorick: { title: '牧魂人', name: '约里克', roles: ['Top'] },
    Yunara: { title: '不破之誓', name: '芸阿娜', roles: ['Support'] },
    Yuumi: { title: '魔法猫咪', name: '悠米', roles: ['Support'] },
    Zaahen: { title: '不落魔锋', name: '亚恒', roles: ['Top'] },
    Zac: { title: '生化魔人', name: '扎克', nicknames: ['粑粑人'], roles: ['Jungle', 'Top'] },
    Zed: { title: '影流之主', name: '劫', nicknames: ['飞镖人'], roles: ['Mid', 'Jungle'] },
    Zeri: { title: '祖安花火', name: '泽丽', roles: ['ADC'] },
    Ziggs: { title: '爆破鬼才', name: '吉格斯', nicknames: ['炸弹人'], roles: ['Mid', 'ADC'] },
    Zilean: { title: '时光守护者', name: '基兰', nicknames: ['老头'], roles: ['Support', 'Mid'] },
    Zoe: { title: '暮光星灵', name: '佐伊', roles: ['Mid'] },
    Zyra: { title: '荆棘之兴', name: '婕拉', roles: ['Support', 'Jungle'] },
}

/**
 * 根据英文 key 获取英雄信息（中文称号 + 中文名 + 分路）。
 * 如果找不到，返回 undefined。
 */
export function getChampionInfo(key: string): ChampionInfo | undefined {
    return CHAMPION_DATA[key]
}
